### ISSUE TITLE
Bug: Kafka consumes the same message twice

### ISSUE THREAD

**Issue by falled10** [airtai/faststream#1090] opened 2023-12-23 17:52 UTC
For some reasons, when you producing a message while consumer is down, and then consumes those messages, consumer consumes the same message twice. Here's an example:

Let's say you have 2 consumers

```python
@broker.subscriber("one_topic", group_id='group', auto_commit=False)
async def base_handler(body: str, msg: KafkaMessage):
    print(body)
    await asyncio.sleep(10)
    print('after one')
````

```python
@broker.subscriber("other_topic", group_id='group', auto_commit=False)
async def error_handler(body):
    print(body)
    print('after other')
```
And while application is down, you will produce 2 messages

```python
await broker.publish("First", topic="one_topic", key=b'1')
await broker.publish("Second", topic="one_topic", key=b'1')
```

After you run your application you will get following logs
<img width="905" alt="image" src="https://github.com/airtai/faststream/assets/37878250/a231ace7-a55a-4ca7-b1e9-be4033960981">

As you may see, the first message with the same id is repeated twice

If I produce those 2 messages after application is fully started, everything works fine

UPD: The problem is because of the same group id for 2 consumers

**Comment by Lancetnik** [comment] 2024-01-22 18:24
Seems like the problem is on **Kafka** settings side, not the framework. I close it for now, but we can reopen, if the problem is in **FastStream**

**Closed by Lancetnik** 2024-01-22 18:24 UTC
Labels: bug
