### ISSUE TITLE
Create cookiecutter project templates in the separated repo

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#569] opened 2023-09-07 18:50 UTC

**Comment by davorrunje** [comment] 2023-09-26 09:40
Duplicate of #746

**Comment by kumaranvpl** [comment] 2023-09-29 06:02
We are going to do this next week

**Comment by kumaranvpl** [comment] 2023-10-11 06:05
Available at https://github.com/airtai/cookiecutter-faststream

**Closed by kumaranvpl** 2023-10-11 06:05 UTC
Labels: duplicate
